### ISSUE TITLE
Not working Solus OS 4.1 Budgie

### ISSUE THREAD

**Issue by ghost** [xulongwu4/solus-nvidia-optimus-manager#8]
Hi,

Thank you so much for your script.

I tried on a dell laptop G5 5587 with a GTX 1060 max-q but it doesn't work.

if I run the command : `lsmod | grep nvidia` or intel, I can see that the driver are loaded.

But I cannot load the nvidia-settings app and when I try to run a game it doesn't work even when using these environment variable: 

`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`

however switching from the intel GPU to Nvidia works just fine.

Any idea?

**Comment by xulongwu4** [comment]
What's the output of `nvidia-optimus-manager status`?

**Comment by ghost** [comment]
It seems that everything is working.

```
nvidia-optimus-manager status
Current profile: hybrid
OpenGL vendor: Intel
Discrete graphics card power status: active

```

**Comment by xulongwu4** [comment]
In hybrid mode, your screen is still rendered by the intel card, not the nvidia card. So `nvidia-settings` won't work in this setting. You need to go to `nvidia` mode to be able to use nvidia to drive your screen.

Try
 ```sudo nvidia-optimus-manager configure nvidia```
and then log out and log back in. `nvidia-settings` should work then.

**Comment by ghost** [comment]
I understand for the nvidia-setting.

However now it seems that the nvidia-settings should be working even in on demand (it works under ubuntu 20.04 and flavours of ubuntu as well)

When in hybrid mode I should be able to use the nvidia card on demand to play games fr exemple, but it doesn't work.

normally these command should do the trick, but they don't work... :

`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`

**Comment by xulongwu4** [comment]
If you want to use the environment variables to control the nvidia graphic card, you don't need to use this script. All you need is a recent linux kernel and a recent version of mesa, and a recent nvidia driver, which solus already ships. However, I spend a little time to try that a while ago and it didn't work for me. So if you are concerned with why `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia` doesn't work, you should report it to Solus's dev track: https://dev.getsol.us.

To be clear, this script is not using any of the environment variables to control the nvidia card and it only relies on the rime-time power management feature of linux kernel. It doesn't require a very recent version of linux kernel or mesa. If you opt to use environment variables such as `__NV_PRIME_RENDER_OFFLOAD` to control prime offload, you don't need this script. One thing to notice is that, even if you can offload your screen to intel card, your nvidia card can still be on. This is because the power management feature of nvidia driver only supports Turing card. In your case, your GTX 1060 max-Q will stay on if you offload your screen to intel card using Nvidia's driver.

**Comment by ghost** [comment]
found the solution to make the render offload work just fine.

create a the file /etc/X11/xorg.conf then copy and paste this to the file :

`Section "ServerLayout"
   Identifier "layout"
   Screen 0 "iGPU"
   Option "AllowNvidiaGpuScreens"
EndSection

Section "Device"
   Identifier "iGPU"
   Driver "modesetting"
   BusID  "PCI:0:2:0"
EndSection

Section "Device"
   Identifier "nvidia"
   Driver "nvidia"
   BusID  "PCI:1:0:0"
EndSection    

Section "Screen"
   Identifier "iGPU"
   Device "iGPU"
EndSection`

However the file is being deleted everytime you are switching gpu.
